services:
  web:
    container_name: e-journal_web
    ports:
      - "80:80"
    build:
      context: ./docker
    depends_on:
      - db
    volumes:
      - ./api/:/var/www/localhost/htdocs/api/
      - ./frontend/:/var/www/localhost/htdocs/frontend/
      - ./docker/logs:/var/www/logs/
      - ./docker/apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    environment:
      PHP_EXTENSION_XDEBUG: 0
      PHP_INI_DIR: /usr/local/etc/php
      TZ: "Europe/Zaporozhye"
      APACHE_LOG_DIR: /var/www/logs
  db:
    container_name: e-journal_db
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_DATABASE
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
